name: CI Workflow
run-name: "${{ github.actor }} triggered ${{ github.event_name }} on branch ${{ github.head_ref || github.ref_name }}"

on:
  push:
    branches:
      - 'feature/*'

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Job 1 passed!"

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: cat non_existent_file.txt

  job3:
    runs-on: ubuntu-latest
    needs: job2
    if: always()
    steps:
      - run: echo "Job 2 result -> ${{ needs.job2.result }}"

      - if: needs.job2.result == 'success'
        run: echo "✅ Success notification - Job 2 passed!"

      - if: needs.job2.result == 'failure'
        run: echo "❌ Failure notification - Job 2 failed!"
